services:

  mysql:
    image: mysql:latest
    container_name: nest-admin-mysql
    env_file:
      - .env
      - .env.production
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    networks:
      - nest-admin-network
  redis:
    image: redis:alpine
    container_name: nest-admin-redis
    env_file:
      - .env
      - .env.production
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - nest-admin-network

networks:
  nest-admin-network:
    driver: bridge